# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_reple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reple',
            name='Post',
            field=models.IntegerField(),
        ),
    ]
