# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-07 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180107_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Blog',
            field=models.SlugField(default='slug'),
        ),
    ]
